### ISSUE TITLE
_Some_ apps do not start

### ISSUE THREAD

**Issue by PeterKawa** [rkokkelk/nl.xseth.dashboardctrl#5]
Hi Roy, while trying to resolve a Q from someone, I discovered DashboardController doesn't start any app on my tablet. All other things work fine though, all permissions are set. 
Any thoughts?

Thanks for the fine app! 
Cheers, Peter

**Comment by rkokkelk** [comment]
Hi Peter, how do you define the app that you select to start the app. 

Do you use the proper app ID for the app that you want to start?

**Comment by PeterKawa** [comment]
Hi Roy, I used the "package name viewer 2.0" from ggle store to reveal the app ID's.
For instance the Calculator ID is com.android.calculator2
When I use the "Start application" action card, and enter [com.android.calculator2], the flow doesn't open the Calc app on the tablet. 
BUT, appearantly I tested exactly those 3 apps which don't respond.
I just tested again with a few more apps, and they do open.
So it seems to be more of an Android issue, than an issue with your app I think.
What are your thoughts on this?

Not showing:
- Calculator: com.android.calculator2 (No) 
- Calendar: com.android.calendar (No) 
-  Show Desktop: com.android.launcher3 (No) ór com.android.systemui (No)

Showing:
- Chromium: org.chromium.chrome (YES)
- Camera: com.android.camera2 (YES) 
- Fotoo: com.bo.fotoo (YES) 
- Spotify: com.spotify.music (YES) 
- Gallery: com.android.gallery3d (YES) 
- Files: com.android.documentsui (YES) 
- Settings: com.android.settings (YES)

**Comment by rkokkelk** [comment]
This is indeed not an issue with the dashboard controller app but with the possibilities within Fully browser. That is the actual app which starts the androids app, the dashboard controller only ensures that Fully browsers starts the appropriate Android app via de REST API.

My guess is that the aforementioned apps require some different set of permissions so that Fully browser is not able to actually starts the application. This is not something I can change within the dashboard controller app. Your best bed is to contact the developers behind Fully browser and ask them why these specific apps cannot be started via fully browser.
